### ISSUE TITLE
Running on Korean Dataset

### ISSUE THREAD

**Issue by watanka** [clovaai/SATRN#1]
Hi,
I'm trying to run this model on korean dataset. I finished training and tried to evaluate, but stuck on UnicodeEncodeError.

It seems to be writing non-english character to file  is causing an error. 

Could you please tell me how to handle the 's' ?
https://github.com/clovaai/SATRN/blob/35e9e94614785367d288d8af0d2883e537b901e6/src/eval.py#L137-L153

I've tried encode('utf-8').decode('utf-8'), and other way around, but didn't work.

Thank you.

**Comment by watanka** [comment]
fixed open('file.txt', 'w') -> open('file.txt', 'utf-8') 
dumb mistake that took so much of my time. now closing.
https://github.com/clovaai/SATRN/blob/35e9e94614785367d288d8af0d2883e537b901e6/src/eval.py#L138

**Comment by MrYANG23** [comment]
hi can you share the dataset ,when I train my dataset ,I met this error

2020-08-27 07:36:09.335495: W tensorflow/core/kernels/data/generator_dataset_op.cc:79] Error occurred when finalizing GeneratorDataset iterator: Invalid argument: Argument 1 is out of range.
	 [[{{node remotecall_train_const}}]]

is the dataset not ture? 
thank you
